import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const manifest = JSON.parse(await readFile(new URL('../mobius.json', import.meta.url)))

test('install contract declares GitHub authority and five-minute review job', () => {
  assert.equal(manifest.id, 'pr-review')
  assert.equal(manifest.permissions.github_access, true)
  assert.equal(manifest.permissions.github_connect, true)
  assert.deepEqual(manifest.schedule, { default: '*/5 * * * *', job: 'job.sh' })
  assert.ok(manifest.source_files.includes('reviewing.md'))
  assert.ok(manifest.source_files.includes('reviewer_runner.py'))
})

test('manual public comment requires a second explicit click', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /Send this comment/)
  assert.match(source, /Post publicly to \{review\.repository\} #\{review\.number\}\?/)
  assert.match(source, /Send comment publicly/)
  assert.match(source, /onClick=\{\(\) => \{ setConfirming\(false\); onSend\(review\) \}\}/)
  assert.doesNotMatch(source, /useEffect\([^)]*sendReviewerComment/)
})

test('background review and discovery updates repaint an already-open inbox', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /storage\.subscribe\('job-state\/ledger\.json'/)
  assert.match(source, /storage\.subscribe\('discovery\.json'/)
  assert.match(source, /setLedger\(value\)/)
  assert.match(source, /stopLedger\?\.\(\); stopDiscovery\?\.\(\)/)
})

test('background failure states distinguish sign-in, usage, and transient model errors', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const domain = await readFile(new URL('../domain.js', import.meta.url), 'utf8')
  assert.match(domain, /provider_setup_required: 'Sign-in needed'/)
  assert.match(domain, /review_agent_setup_required: 'Check agents'/)
  assert.match(domain, /waiting_for_capacity: 'Usage wait'/)
  assert.match(domain, /waiting_for_model: 'Retry queued'/)
  assert.match(domain, /waiting_for_evidence: 'Refreshing'/)
  assert.match(domain, /reviewing: 'Reviewing'/)
  assert.doesNotMatch(source, /status === 'skipped'/)
  assert.doesNotMatch(source, /Waiting for model capacity/)
})

test('inbox leads with actionable review health instead of historical vanity metrics', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /countOpenPullRequestsWithFindings\(visiblePulls, ledger\)/)
  assert.match(source, /<span>open PRs with findings<\/span>/)
  assert.match(source, /<span>automation<\/span>/)
  assert.match(source, /className="rv-inbox-layout"/)
  assert.doesNotMatch(source, /review target/)
  assert.doesNotMatch(source, /revisions reviewed<\/span>/)
  assert.doesNotMatch(source, /<h3>Automation state<\/h3>/)
  assert.doesNotMatch(source, /<h3>Review posture<\/h3>/)
})

test('review details show one exact GitHub comment without a duplicated finding view', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /<summary>Review comment<\/summary>/)
  assert.match(source, /<div className="rv-comment-preview"><pre>\{review\.draft_comment\}<\/pre><\/div>/)
  assert.doesNotMatch(source, /review\.findings\.map/)
  assert.doesNotMatch(source, /Prepare a fix in Contribute/)
})

test('inbox groups cards by review status without repeating a card status line', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /INBOX_GROUPS = \[[\s\S]*?'awaiting'[\s\S]*?'findings'[\s\S]*?'clear'[\s\S]*?'skipped'/)
  assert.match(source, /<ReviewGroup key=\{group\.id\}/)
  assert.match(source, /className="rv-group-count"[\s\S]*?>\{group\.items\.length\}<\/span>/)
  assert.match(source, /<span className="rv-card-sent"><Check size=\{12\} \/> Sent<\/span>/)
  assert.doesNotMatch(source, /<span>Reviewer<\/span>/)
  assert.doesNotMatch(source, /rv-review-state/)
  assert.match(source, /if \(readiness\.code === 'posted'\) return null/)
  assert.doesNotMatch(source, /Comment sent/)
  assert.doesNotMatch(source, /View on GitHub/)
})

test('line changes distinguish additions from deletions by color', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const theme = await readFile(new URL('../theme.js', import.meta.url), 'utf8')
  assert.match(source, /className="rv-additions">\+\{pr\.additions\}/)
  assert.match(source, /className="rv-deletions">−\{pr\.deletions\}/)
  assert.match(theme, /\.rv-additions \{ color:#84d7ac; \}/)
  assert.match(theme, /\.rv-deletions \{ color:#e88378; \}/)
})

test('risk badge shares the PR heading and queued reviews expose an accessible retry', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const theme = await readFile(new URL('../theme.js', import.meta.url), 'utf8')
  const storage = await readFile(new URL('../storage.js', import.meta.url), 'utf8')
  assert.match(source, /<div className="rv-pr-heading">[\s\S]*?<span className=\{`rv-risk \$\{risk\}`\}>\{risk\}<\/span>/)
  assert.match(source, /groupId === 'retry'[\s\S]*?<RetryReviewAction/)
  assert.match(source, /aria-label=\{label\}/)
  assert.match(source, /await requestReviewRetry\(review\)[\s\S]*?await runReviewerJob\(token, appId\)/)
  assert.match(storage, /job-state\/retry-requests\/\$\{identity\}\.json/)
  assert.doesNotMatch(theme, /\.rv-pr > \.rv-risk/)
})

test('repository selection stays in place and groups watched repos first', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  assert.match(source, /useLayoutEffect\(\(\) => \{[\s\S]*?listRef\.current\.scrollTop/)
  assert.match(source, /onScroll=\{event => \{ preservedScrollTop\.current = event\.currentTarget\.scrollTop \}\}/)
  assert.match(source, /selected: merged\.filter[\s\S]*?\.sort\(alphabetically\)/)
  assert.match(source, /available: merged\.filter[\s\S]*?\.sort\(alphabetically\)/)
  assert.match(source, /const rows = \[[\s\S]*?type: 'divider'[\s\S]*?rows\.map/)
  assert.match(source, /className="rv-repo-divider" role="separator"/)
  assert.match(source, /refreshSelectedPulls\(next\.selectedRepos\)/)
  assert.doesNotMatch(source, /\[appId, token, settings\.selectedRepos\]/)
})

test('automation surfaces one status bar and two clear settings sections', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const theme = await readFile(new URL('../theme.js', import.meta.url), 'utf8')
  assert.match(source, /className="rv-automation-statusbar"[\s\S]*?Status:[\s\S]*?\{automationState\}[\s\S]*?Pause/)
  assert.match(source, /<h2>General settings<\/h2>/)
  assert.match(source, /<h2>Agent settings<\/h2>/)
  assert.match(source, /Daily automation limit/)
  assert.match(source, /Post reviews automatically/)
  assert.match(source, /Comments per PR/)
  assert.doesNotMatch(source, /Standing behavior|Reviewer automation|<h3>Publishing<\/h3>/)
  assert.doesNotMatch(source, /Review draft pull requests|Review new revisions automatically/)
  assert.doesNotMatch(source, /Automatic comments per day|Hold automatic comments|Approve current setup/)
  assert.match(theme, /\.rv-automation-statusbar \{[^}]*display:flex/)
  assert.match(theme, /\.rv-switch \{[^}]*border:1px[^}]*background:/)
  assert.match(theme, /\.rv-switch\.on \{[^}]*background:/)
})

test('one posting switch owns approval and one daily limit owns both ceilings', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const domain = await readFile(new URL('../domain.js', import.meta.url), 'utf8')
  const runner = await readFile(new URL('../reviewer_runner.py', import.meta.url), 'utf8')
  assert.match(source, /automationStateLabel\(a, ledger\)/)
  assert.match(source, /postingSwitchValue[\s\S]*?a\.automaticPosting && grant\?\.enabled && grantMatches/)
  assert.match(source, /postingSwitchValue[\s\S]*?disabled=\{!postingStateKnown \|\| grantState === 'saving'\}/)
  assert.match(source, /grantConfigurationMatchesSettings[\s\S]*?toggleReviewerGrant\(token, appId, true\)[\s\S]*?grantReviewerPosting/)
  assert.match(source, /daily_post_ceiling: Number\(approvalSettings\.automation\.dailyLimit\)/)
  assert.match(source, /max_rounds_per_pr: Number\(approvalSettings\.automation\.commentsPerPr\)/)
  assert.match(source, /const postsToday = dailyEventCount\(ledger, 'post'\)/)
  assert.match(source, /postingRequestRef\.current[\s\S]*?finally \{[\s\S]*?postingRequestRef\.current = false/)
  assert.match(source, /Promise\.allSettled\(\[[\s\S]*?fetchReviewerGrant[\s\S]*?const github = await fetchGitHubStatus/)
  assert.doesNotMatch(domain, /includeDrafts|privateMode:|revisionsPerDay:|postsPerDay:|roundsPerPr:/)
  assert.doesNotMatch(runner, /settings\["include_drafts"\]|not settings\["automatic"\]/)
  assert.match(runner, /try_post_completed_review\([\s\S]*?latest_settings, bundle, record, posting_grant/)
})

test('automation owns distinct no-tool Scout and Verifier choices', async () => {
  const source = await readFile(new URL('../index.jsx', import.meta.url), 'utf8')
  const api = await readFile(new URL('../api.js', import.meta.url), 'utf8')
  const runner = await readFile(new URL('../reviewer_runner.py', import.meta.url), 'utf8')
  assert.match(source, /<h2>Agent settings<\/h2>/)
  assert.match(source, /role="Scout agent"/)
  assert.match(source, /role="Verifier agent"/)
  assert.match(source, /These choices apply only to Reviewer/)
  assert.match(source, /Claude · no tools/)
  assert.match(source, /Claude configured/)
  assert.match(source, /reviewEffortsForModel\(model, available\)/)
  assert.match(api, /\/api\/auth\/providers\/models/)
  assert.match(api, /\/api\/auth\/providers\/status/)
  assert.match(runner, /review_agents=settings\["review_agents"\]/)
  assert.match(runner, /"review_agents": \{[\s\S]*?"scout": scout_choice, "verifier": verifier_choice/)
})
